### ISSUE TITLE
Is there any way to ignore node_modules?

### ISSUE THREAD

**Issue by ymatuhin** [folke/vscode-monorepo-workspace#82] opened 2021-02-14 16:40 UTC
In my case when I do "Select workspace folders" It shows me modules from my project's dependencies (from node_module folder). 

This doesn't help
```
  "files.exclude": {
    "**/node_modules": true
  }
```

**Comment by ckot** [comment] 2021-02-28 02:56
I'm seeing this to.  didn't use to.  I haven't been working with a monorepo for several months, so I don't know when this changed.

At least this issue made me aware that yarn isn't properly hoisting these deps to the top-level node_modules dir :)

**Comment by ckot** [comment] 2021-02-28 03:06
@folke   I just downgraded to v 1.2 after seeing how that resolved issue #78  and it fixed this problem for me.  perhaps the 2 are related with it wanting to list node_modules as packages?  

now to figure out what is going on with my yarn workspaces node_modules not hoisting properly :(

**Comment by ckot** [comment] 2021-02-28 03:22
I just realized that the latest package I added didn't have a .gitignore.  after I did that, v 1.3 works just fine.

**Comment by folke** [comment] 2021-02-28 07:04
@ckot I'm not able to reproduce this unfortunately.

In my monorepo, I did have an entry for `node_modules` in `.gitignore`, but even when I delete it, **Select Workspace Folders** still only show my packages.

Could you maybe share the configuration of your Yarn workspace?

**Comment by folke** [comment] 2021-02-28 07:09
I assume this is caused by a change I did to `ultra-runner`, which is the basis for `monorepo-workspace`.
https://github.com/folke/ultra-runner/issues/70
https://github.com/folke/ultra-runner/issues/85

**Comment by folke** [comment] 2021-02-28 07:10
@ymatuhin could you also share your workspace config?

**Comment by folke** [comment] 2021-02-28 07:13
The odd behaviour is probably caused by this change: https://github.com/folke/ultra-runner/commit/d4afba992fee66e28edc98505b774901013c6307

Still, with a correct workspace configuration this should not happen I think.

**Comment by folke** [comment] 2021-02-28 07:45
I just release a new version of **ultra** and **monorepo workspace** that always excludes `node_modules`, regardless of the workspace configuration. It's probably a sensible default we always want.

Can you both check if this now works as expected, even without specifying `node_modules` in your `.gitignore`?

**Comment by ckot** [comment] 2021-03-01 05:24
@folke  yeah v3.1 seems to work without the need for node_modules being filtered by a .gitignore

what info do you need regarding yarn workspaces config?

**Comment by folke** [comment] 2021-03-01 06:25
Great, closing this

**Closed** 2021-03-01 06:25 UTC
